"""
Django settings for LKEducation project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4%d_a)&&lpr9qvd8^ybc$^qgajyj^lwt$_2qn9^*(pgvrt3cz#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    'SiteVitrine.apps.SitevitrineConfig',
    'Gestion.apps.GestionConfig',
    'compressor',  # new
]

AUTH_USER_MODEL = 'SiteVitrine.user'

PHONENUMBER_DEFAULT_REGION = 'CM'  # Replace with your desired default region

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_COOKIE_AGE = 1800  # 30 minutes (exprimé en secondes)

ROOT_URLCONF = 'LKEducation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

#COMPRESS_URL = '/static/'

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

WSGI_APPLICATION = 'LKEducation.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
    #'path.to.YourCustomBackend',  # Replace 'path.to.YourCustomBackend' with the actual path to your custom backend
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
    {
        'NAME': 'SiteVitrine.validators.ContainsLetterValidator',
    },
    {
        'NAME': 'SiteVitrine.validators.ContainsNumberValidator',
    },
    {
        'NAME': 'SiteVitrine.validators.ContainsSpecialCaracterValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'SiteVitrine/static/')
STATICFILES_DIRS = [
    BASE_DIR /"static"/"admin",
    BASE_DIR /"static"/"src",
    BASE_DIR /"static"/"dist",
    BASE_DIR /"static"/"build",
    BASE_DIR /"static"/"plugins",
    BASE_DIR /"static"/"js",
    BASE_DIR /"static"/"cache"
]
MEDIA_URL='/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL SETTINGS 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'makenabgte@gmail.com' #adresse e-mail de l'expéditeur par défaut pour les e-mails sortants
EMAIL_HOST_PASSWORD = 'qgkspfenbflevqsb'
EMAIL_USE_TLS = True
#EMAIL_USE_SSL = False

#LOGIN SETTINGS 
LOGIN_URL = 'login' #Cela signifie que si un utilisateur non authentifié tente 
 #d'accéder à une page nécessitant une connexion, Django le redirigera automatiquement vers l'URL de connexion 'login'