# Generated by Django 4.2.1 on 2023-06-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=' ', upload_to='location'),
        ),
        migrations.AlterField(
            model_name='document',
            name='intitule',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='location'),
        ),
    ]
