# Generated by Django 4.2.1 on 2023-06-14 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0002_rename_admin_user_is_admin_remove_user_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
