# Generated by Django 4.2.1 on 2023-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.TextField(default='You'),
        ),
    ]
