# Generated by Django 4.2.1 on 2023-06-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0003_user_is_staff_alter_user_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
