# Generated by Django 4.2.1 on 2023-07-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0003_alter_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
