# Generated by Django 4.2.1 on 2023-06-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0004_alter_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
