# Generated by Django 4.2.1 on 2023-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0005_contact_remove_user_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nom',
            new_name='nom_et_prenom',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='prenom',
        ),
        migrations.AddField(
            model_name='contact',
            name='sujet',
            field=models.CharField(default='', max_length=50),
        ),
    ]
