# Generated by Django 4.2.1 on 2023-07-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0007_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
