# Generated by Django 4.2.1 on 2023-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0008_user_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='est_repondu',
            field=models.BooleanField(default=False),
        ),
    ]
