# Generated by Django 4.2.1 on 2023-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
