# Generated by Django 4.2.1 on 2023-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0009_contact_est_repondu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lieu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nationalité',
            field=models.CharField(default='', max_length=50),
        ),
    ]
