# Generated by Django 4.2.1 on 2023-12-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteVitrine', '0010_user_lieu_user_nationalité'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Domaine_etudes_en_France',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Etudes_en_cours',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='dernier_diplome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='moyenne_et_annee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
